// lib/countries.ts
export const allCountries = [
  { id: "af", name: "アフガニスタン", continent: "Asia" },
  { id: "al", name: "アルバニア", continent: "Europe" },
  { id: "dz", name: "アルジェリア", continent: "Africa" },
  { id: "ad", name: "アンドラ", continent: "Europe" },
  { id: "ao", name: "アンゴラ", continent: "Africa" },
  { id: "ag", name: "アンティグア・バーブーダ", continent: "North America" },
  { id: "ar", name: "アルゼンチン", continent: "South America" },
  { id: "am", name: "アルメニア", continent: "Asia" },
  { id: "au", name: "オーストラリア", continent: "Oceania" },
  { id: "at", name: "オーストリア", continent: "Europe" },
  { id: "az", name: "アゼルバイジャン", continent: "Asia" },
  { id: "bs", name: "バハマ", continent: "North America" },
  { id: "bh", name: "バーレーン", continent: "Asia" },
  { id: "bd", name: "バングラデシュ", continent: "Asia" },
  { id: "bb", name: "バルバドス", continent: "North America" },
  { id: "by", name: "ベラルーシ", continent: "Europe" },
  { id: "be", name: "ベルギー", continent: "Europe" },
  { id: "bz", name: "ベリーズ", continent: "North America" },
  { id: "bj", name: "ベナン", continent: "Africa" },
  { id: "bt", name: "ブータン", continent: "Asia" },
  { id: "bo", name: "ボリビア", continent: "South America" },
  { id: "ba", name: "ボスニア・ヘルツェゴビナ", continent: "Europe" },
  { id: "bw", name: "ボツワナ", continent: "Africa" },
  { id: "br", name: "ブラジル", continent: "South America" },
  { id: "bn", name: "ブルネイ", continent: "Asia" },
  { id: "bg", name: "ブルガリア", continent: "Europe" },
  { id: "bf", name: "ブルキナファソ", continent: "Africa" },
  { id: "bi", name: "ブルンジ", continent: "Africa" },
  { id: "cv", name: "カーボベルデ", continent: "Africa" },
  { id: "kh", name: "カンボジア", continent: "Asia" },
  { id: "cm", name: "カメルーン", continent: "Africa" },
  { id: "ca", name: "カナダ", continent: "North America" },
  { id: "cf", name: "中央アフリカ共和国", continent: "Africa" },
  { id: "td", name: "チャド", continent: "Africa" },
  { id: "cl", name: "チリ", continent: "South America" },
  { id: "cn", name: "中国", continent: "Asia" },
  { id: "co", name: "コロンビア", continent: "South America" },
  { id: "km", name: "コモロ", continent: "Africa" },
  { id: "cg", name: "コンゴ共和国", continent: "Africa" },
  { id: "cd", name: "コンゴ民主共和国", continent: "Africa" },
  { id: "cr", name: "コスタリカ", continent: "North America" },
  { id: "ci", name: "コートジボワール", continent: "Africa" },
  { id: "hr", name: "クロアチア", continent: "Europe" },
  { id: "cu", name: "キューバ", continent: "North America" },
  { id: "cy", name: "キプロス", continent: "Asia" },
  { id: "cz", name: "チェコ", continent: "Europe" },
  { id: "dk", name: "デンマーク", continent: "Europe" },
  { id: "dj", name: "ジブチ", continent: "Africa" },
  { id: "dm", name: "ドミニカ国", continent: "North America" },
  { id: "do", name: "ドミニカ共和国", continent: "North America" },
  { id: "ec", name: "エクアドル", continent: "South America" },
  { id: "eg", name: "エジプト", continent: "Africa" },
  { id: "sv", name: "エルサルバドル", continent: "North America" },
  { id: "gq", name: "赤道ギニア", continent: "Africa" },
  { id: "er", name: "エリトリア", continent: "Africa" },
  { id: "ee", name: "エストニア", continent: "Europe" },
  { id: "sz", name: "エスワティニ", continent: "Africa" },
  { id: "et", name: "エチオピア", continent: "Africa" },
  { id: "fj", name: "フィジー", continent: "Oceania" },
  { id: "fi", name: "フィンランド", continent: "Europe" },
  { id: "fr", name: "フランス", continent: "Europe" },
  { id: "ga", name: "ガボン", continent: "Africa" },
  { id: "gm", name: "ガンビア", continent: "Africa" },
  { id: "ge", name: "ジョージア", continent: "Asia" },
  { id: "de", name: "ドイツ", continent: "Europe" },
  { id: "gh", name: "ガーナ", continent: "Africa" },
  { id: "gr", name: "ギリシャ", continent: "Europe" },
  { id: "gd", name: "グレナダ", continent: "North America" },
  { id: "gt", name: "グアテマラ", continent: "North America" },
  { id: "gn", name: "ギニア", continent: "Africa" },
  { id: "gw", name: "ギニアビサウ", continent: "Africa" },
  { id: "gy", name: "ガイアナ", continent: "South America" },
  { id: "ht", name: "ハイチ", continent: "North America" },
  { id: "hn", name: "ホンジュラス", continent: "North America" },
  { id: "hu", name: "ハンガリー", continent: "Europe" },
  { id: "is", name: "アイスランド", continent: "Europe" },
  { id: "in", name: "インド", continent: "Asia" },
  { id: "id", name: "インドネシア", continent: "Asia" },
  { id: "ir", name: "イラン", continent: "Asia" },
  { id: "iq", name: "イラク", continent: "Asia" },
  { id: "ie", name: "アイルランド", continent: "Europe" },
  { id: "il", name: "イスラエル", continent: "Asia" },
  { id: "it", name: "イタリア", continent: "Europe" },
  { id: "jm", name: "ジャマイカ", continent: "North America" },
  { id: "jp", name: "日本", continent: "Asia" },
  { id: "jo", name: "ヨルダン", continent: "Asia" },
  { id: "kz", name: "カザフスタン", continent: "Asia" },
  { id: "ke", name: "ケニア", continent: "Africa" },
  { id: "ki", name: "キリバス", continent: "Oceania" },
  { id: "kp", name: "北朝鮮", continent: "Asia" },
  { id: "kr", name: "韓国", continent: "Asia" },
  { id: "kw", name: "クウェート", continent: "Asia" },
  { id: "kg", name: "キルギス", continent: "Asia" },
  { id: "la", name: "ラオス", continent: "Asia" },
  { id: "lv", name: "ラトビア", continent: "Europe" },
  { id: "lb", name: "レバノン", continent: "Asia" },
  { id: "ls", name: "レソト", continent: "Africa" },
  { id: "lr", name: "リベリア", continent: "Africa" },
  { id: "ly", name: "リビア", continent: "Africa" },
  { id: "li", name: "リヒテンシュタイン", continent: "Europe" },
  { id: "lt", name: "リトアニア", continent: "Europe" },
  { id: "lu", name: "ルクセンブルク", continent: "Europe" },
  { id: "mg", name: "マダガスカル", continent: "Africa" },
  { id: "mw", name: "マラウイ", continent: "Africa" },
  { id: "my", name: "マレーシア", continent: "Asia" },
  { id: "mv", name: "モルディブ", continent: "Asia" },
  { id: "ml", name: "マリ", continent: "Africa" },
  { id: "mt", name: "マルタ", continent: "Europe" },
  { id: "mh", name: "マーシャル諸島", continent: "Oceania" },
  { id: "mr", name: "モーリタニア", continent: "Africa" },
  { id: "mu", name: "モーリシャス", continent: "Africa" },
  { id: "mx", name: "メキシコ", continent: "North America" },
  { id: "fm", name: "ミクロネシア連邦", continent: "Oceania" },
  { id: "md", name: "モルドバ", continent: "Europe" },
  { id: "mc", name: "モナコ", continent: "Europe" },
  { id: "mn", name: "モンゴル", continent: "Asia" },
  { id: "me", name: "モンテネグロ", continent: "Europe" },
  { id: "ma", name: "モロッコ", continent: "Africa" },
  { id: "mz", name: "モザンビーク", continent: "Africa" },
  { id: "mm", name: "ミャンマー", continent: "Asia" },
  { id: "na", name: "ナミビア", continent: "Africa" },
  { id: "nr", name: "ナウル", continent: "Oceania" },
  { id: "np", name: "ネパール", continent: "Asia" },
  { id: "nl", name: "オランダ", continent: "Europe" },
  { id: "nz", name: "ニュージーランド", continent: "Oceania" },
  { id: "ni", name: "ニカラグア", continent: "North America" },
  { id: "ne", name: "ニジェール", continent: "Africa" },
  { id: "ng", name: "ナイジェリア", continent: "Africa" },
  { id: "mk", name: "北マケドニア", continent: "Europe" },
  { id: "no", name: "ノルウェー", continent: "Europe" },
  { id: "om", name: "オマーン", continent: "Asia" },
  { id: "pk", name: "パキスタン", continent: "Asia" },
  { id: "pw", name: "パラオ", continent: "Oceania" },
  { id: "pa", name: "パナマ", continent: "North America" },
  { id: "pg", name: "パプアニューギニア", continent: "Oceania" },
  { id: "py", name: "パラグアイ", continent: "South America" },
  { id: "pe", name: "ペルー", continent: "South America" },
  { id: "ph", name: "フィリピン", continent: "Asia" },
  { id: "pl", name: "ポーランド", continent: "Europe" },
  { id: "pt", name: "ポルトガル", continent: "Europe" },
  { id: "qa", name: "カタール", continent: "Asia" },
  { id: "ro", name: "ルーマニア", continent: "Europe" },
  { id: "ru", name: "ロシア", continent: "Europe" },
  { id: "rw", name: "ルワンダ", continent: "Africa" },
  { id: "kn", name: "セントクリストファー・ネイビス", continent: "North America" },
  { id: "lc", name: "セントルシア", continent: "North America" },
  { id: "vc", name: "セントビンセントおよびグレナディーン諸島", continent: "North America" },
  { id: "ws", name: "サモア", continent: "Oceania" },
  { id: "sm", name: "サンマリノ", continent: "Europe" },
  { id: "st", name: "サントメ・プリンシペ", continent: "Africa" },
  { id: "sa", name: "サウジアラビア", continent: "Asia" },
  { id: "sn", name: "セネガル", continent: "Africa" },
  { id: "rs", name: "セルビア", continent: "Europe" },
  { id: "sc", name: "セーシェル", continent: "Africa" },
  { id: "sl", name: "シエラレオネ", continent: "Africa" },
  { id: "sg", name: "シンガポール", continent: "Asia" },
  { id: "sk", name: "スロバキア", continent: "Europe" },
  { id: "si", name: "スロベニア", continent: "Europe" },
  { id: "sb", name: "ソロモン諸島", continent: "Oceania" },
  { id: "so", name: "ソマリア", continent: "Africa" },
  { id: "za", name: "南アフリカ", continent: "Africa" },
  { id: "ss", name: "南スーダン", continent: "Africa" },
  { id: "es", name: "スペイン", continent: "Europe" },
  { id: "lk", name: "スリランカ", continent: "Asia" },
  { id: "sd", name: "スーダン", continent: "Africa" },
  { id: "sr", name: "スリナム", continent: "South America" },
  { id: "se", name: "スウェーデン", continent: "Europe" },
  { id: "ch", name: "スイス", continent: "Europe" },
  { id: "sy", name: "シリア", continent: "Asia" },
  { id: "tj", name: "タジキスタン", continent: "Asia" },
  { id: "tz", name: "タンザニア", continent: "Africa" },
  { id: "th", name: "タイ", continent: "Asia" },
  { id: "tl", name: "東ティモール", continent: "Asia" },
  { id: "tg", name: "トーゴ", continent: "Africa" },
  { id: "to", name: "トンガ", continent: "Oceania" },
  { id: "tt", name: "トリニダード・トバゴ", continent: "North America" },
  { id: "tn", name: "チュニジア", continent: "Africa" },
  { id: "tr", name: "トルコ", continent: "Asia" },
  { id: "tm", name: "トルクメニスタン", continent: "Asia" },
  { id: "tv", name: "ツバル", continent: "Oceania" },
  { id: "ug", name: "ウガンダ", continent: "Africa" },
  { id: "ua", name: "ウクライナ", continent: "Europe" },
  { id: "ae", name: "アラブ首長国連邦", continent: "Asia" },
  { id: "gb", name: "イギリス", continent: "Europe" },
  { id: "us", name: "アメリカ合衆国", continent: "North America" },
  { id: "uy", name: "ウルグアイ", continent: "South America" },
  { id: "uz", name: "ウズベキスタン", continent: "Asia" },
  { id: "vu", name: "バヌアツ", continent: "Oceania" },
  { id: "ve", name: "ベネズエラ", continent: "South America" },
  { id: "vn", name: "ベトナム", continent: "Asia" },
  { id: "ye", name: "イエメン", continent: "Asia" },
  { id: "zm", name: "ザンビア", continent: "Africa" },
  { id: "zw", name: "ジンバブエ", continent: "Africa" },
]

export const TOTAL_UN_MEMBERS = allCountries.length // 195
